name: monorepo-preview-release

description: Action to release packages in a monorepo with a PR related tag

inputs:
  github_token:
    description: Token for authentication with GitHub API
    required: true

runs:
  using: composite

  steps:
    - name: 🚀 Preview release
      run: bun ${{ github.action_path }}/src/index.ts
      shell: bash
      with:
        github_token: ${{ inputs.github_token }}
