name: monorepo-preview-release

description: Action to release packages in a monorepo with a PR related tag

inputs:
  pr_number:
    description: Number of the pull request to use for tagging
    required: true

  auth_token:
    description: Token for authentication with npm registry
    required: false

  github_token:
    description: Token for authentication with GitHub API
    required: true

runs:
  using: composite

  steps:
    - name: 🚀 Preview release
      run: bun ${{ github.action_path }}/src/index.ts
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr_number }}
        AUTH_TOKEN: ${{ inputs.auth_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
