name: railway-redeploy

description: Action to trigger a redeploy of a railway service

inputs:
  service_id: 
    description: ID of the Railway service to redeploy
    required: true

  railway_token:
    description: API token for authentication with Railway
    required: true

  railway_api:
    description: GraphQL API URL for Railway
    required: false
    default: "https://backboard.railway.com/graphql/v2"

runs:
  using: composite

  steps:
    - name: 🚀 Redeploy to Railway
      run: bun ${{ github.action_path }}/src/index.ts
      shell: bash
