name: railway-redeploy

description: Action to trigger a redeploy of a Railway service via GraphQL API.

inputs:
  project_id: 
    description: ID of the Railway project where the service is located
    required: true

  environment:
    description: Environment of the Railway service (e.g., production, development)
    required: true

  service_name:
    description: Name of the Railway service to redeploy
    required: true

  api_token:
    description: API token for authentication with Railway
    required: true

  api_url:
    description: GraphQL API URL for Railway
    required: false
    default: "https://backboard.railway.com/graphql/v2"

outputs:
  service_url:
    value: ${{ steps.redeploy.outputs.service_url }}
    description: URL of the redeployed service

runs:
  using: composite

  steps:
    - name: 🚀 Redeploy to Railway
      id: redeploy
      run: bun ${{ github.action_path }}/src/index.ts
      shell: bash
      env:
        RAILWAY_PROJECT_ID: ${{ inputs.project_id }}
        RAILWAY_ENVIRONMENT: ${{ inputs.environment }}
        RAILWAY_SERVICE_NAME: ${{ inputs.service_name }}
        RAILWAY_API_TOKEN: ${{ inputs.api_token }}
        RAILWAY_API_URL: ${{ inputs.api_url }}
