name: setup-pnpm

description: Prepare PNPM, cache dependencies, and install dependencies

runs:
  using: composite

  steps:
    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        run_install: false

    - name: 📦 Update npm
      shell: bash
      run: |
        if command -v sudo >/dev/null 2>&1; then
          sudo npm install -g npm@11
        else
          npm install -g npm@11
        fi

    - name: 🫙 Export pnpm store path
      id: pnpm-config
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: 🔑 Export cache rotation key
      id: cache-rotation
      shell: bash
      run: |
        echo "ROTATION_KEY=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

    - name: 🔁 Cache dependencies
      uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.ROTATION_KEY }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.ROTATION_KEY }}-

    - name: 📥 Install dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash # required for composite actions

    - name: 🔍 Log versions
      shell: bash
      run: |
        echo "pnpm version: $(pnpm -v)"
        echo "npm version: $(npm -v)"
