name: preview-release

description: Action to release a standalone library with a PR related tag

inputs:
  npm_token:
    description: Token for authentication with npm registry
    required: false

  working_directory:
    description: Directory containing the package to publish
    required: false
    default: "."

  vland_bot_url:
    description: URL of the vland-bot server
    required: false
    default: "https://bot.variable.land"

runs:
  using: node24
  main: dist/index.js
